---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Tagged/Release"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      # Pattern matched against refs/tags
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  repository:
    name: "Repository"
    uses: os-climate/osc-github-devops/.github/workflows/repository.yaml@main
    permissions:
      contents: read

  github-release:
    name: "Release"
    if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[release]')
    uses: os-climate/osc-github-devops/.github/workflows/github-release.yaml@main
    needs:
      - repository
    permissions:
      # Needed both here and in the called workflow
      contents: write
    with:
      build_tag: ${{ needs.repository.outputs.build_tag }}
