---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Tagged/Release"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      # Pattern matched against refs/tags
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  github-release:
    name: "GitHub Release"
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "GitHub Release"
        uses: os-climate/osc-github-devops/.github/actions/github-release-action@main
        with:
          build_tag: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
